// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/zhangsifeng92/geos/log"
)

// template type Exception(PARENT,CODE,WHAT)

var ExplainedExceptionName = reflect.TypeOf(ExplainedException{}).Name()

type ExplainedException struct {
	Exception
	Elog log.Messages
}

func NewExplainedException(parent Exception, message log.Message) *ExplainedException {
	return &ExplainedException{parent, log.Messages{message}}
}

func (e ExplainedException) Code() int64 {
	return 9000000
}

func (e ExplainedException) Name() string {
	return ExplainedExceptionName
}

func (e ExplainedException) What() string {
	return "explained exception,see error log"
}

func (e *ExplainedException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e ExplainedException) GetLog() log.Messages {
	return e.Elog
}

func (e ExplainedException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e ExplainedException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e ExplainedException) String() string {
	return e.DetailMessage()
}

func (e ExplainedException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: 9000000,
		Name: ExplainedExceptionName,
		What: "explained exception,see error log",
	}

	return json.Marshal(except)
}

func (e ExplainedException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*ExplainedException):
		callback(&e)
		return true
	case func(ExplainedException):
		callback(e)
		return true
	default:
		return false
	}
}
