// Code generated by gotemplate. DO NOT EDIT.

package exception

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strconv"

	"github.com/zhangsifeng92/geos/log"
)

// template type Exception(PARENT,CODE,WHAT)

var CanceledExceptionName = reflect.TypeOf(CanceledException{}).Name()

type CanceledException struct {
	Exception
	Elog log.Messages
}

func NewCanceledException(parent Exception, message log.Message) *CanceledException {
	return &CanceledException{parent, log.Messages{message}}
}

func (e CanceledException) Code() int64 {
	return CanceledExceptionCode
}

func (e CanceledException) Name() string {
	return CanceledExceptionName
}

func (e CanceledException) What() string {
	return "Canceled"
}

func (e *CanceledException) AppendLog(l log.Message) {
	e.Elog = append(e.Elog, l)
}

func (e CanceledException) GetLog() log.Messages {
	return e.Elog
}

func (e CanceledException) TopMessage() string {
	for _, l := range e.Elog {
		if msg := l.GetMessage(); len(msg) > 0 {
			return msg
		}
	}
	return e.String()
}

func (e CanceledException) DetailMessage() string {
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(int(e.Code())))
	buffer.WriteByte(' ')
	buffer.WriteString(e.Name())
	buffer.Write([]byte{':', ' '})
	buffer.WriteString(e.What())
	buffer.WriteByte('\n')
	for _, l := range e.Elog {
		buffer.WriteByte('[')
		buffer.WriteString(l.GetMessage())
		buffer.Write([]byte{']', ' '})
		buffer.WriteString(l.GetContext().String())
		buffer.WriteByte('\n')
	}
	return buffer.String()
}

func (e CanceledException) String() string {
	return e.DetailMessage()
}

func (e CanceledException) MarshalJSON() ([]byte, error) {
	type Exception struct {
		Code int64  `json:"code"`
		Name string `json:"name"`
		What string `json:"what"`
	}

	except := Exception{
		Code: CanceledExceptionCode,
		Name: CanceledExceptionName,
		What: "Canceled",
	}

	return json.Marshal(except)
}

func (e CanceledException) Callback(f interface{}) bool {
	switch callback := f.(type) {
	case func(*CanceledException):
		callback(&e)
		return true
	case func(CanceledException):
		callback(e)
		return true
	default:
		return false
	}
}
